FROM debian

RUN apt-get update -y && apt-get install -y apache2 php php-mysql git
#Env do apache
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_PID_FILE /var/run/apache2/apache2.pid
ENV APACHE_SERVER_NAME localhost

VOLUME [ "/var/www/html/" ]

LABEL description="AmbientePHP"
LABEL version="1.0"

WORKDIR /var/www/html/
COPY apache-conf /etc/apache2/apache2.conf
 
# Expor a porta
EXPOSE 80
 
# rodar apache
CMD ["/usr/sbin/apache2ctl", "-DFOREGROUND"]
